# fly.toml app configuration file generated for vilcos-site on 2025-05-08T23:06:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vilcos-site'
primary_region = 'iad'

[build]
  dockerfile = 'docker-deploy/Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
